name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd src
      run: cd src
    - name: make all
      run: make all
    - name: ./dfcpu
      run: ./dfcpu
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
