name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd src
      run: cd src
    - name: gcc
      run: gcc dfcpu.c -o dfcpu -I./include -nostartfiles
    - name: ./dfcpu
      run: ./dfcpu
